### ISSUE TITLE
Cannot find module: 'dfx-generated/backend'.

### ISSUE THREAD

**Issue by Forpee** [gabrielnic/motoko-cdn#1]
When i use dfx deploy i get this: 

Failed to compile.
./src/agent.ts
Cannot find module: 'dfx-generated/backend'. Make sure this package is installed.

**Comment by gabrielnic** [comment]
Hi, it's on the old dfx and I haven't upgraded this yet. Will do it this weekend.

**Comment by ruby-rhino** [comment]
same issue here, dfx version mismatch. any updates on this, please?

**Comment by gabrielnic** [comment]
I just released a new version to fix this.
